# Numpy

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [10]:
test_range = np.arange(0, 10, 2)

In [11]:
test_range

array([0, 2, 4, 6, 8])

In [15]:
np_zero = np.zeros((5,5, 5))
np_zero

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(100)

array([0.66406186, 0.9468724 , 0.84043893, 0.95494003, 0.72079513,
       0.86637817, 0.09041332, 0.94606674, 0.40178465, 0.81481412,
       0.67058092, 0.0995092 , 0.83735927, 0.37287525, 0.3707341 ,
       0.94007484, 0.46925669, 0.97471153, 0.24638566, 0.64206637,
       0.88029201, 0.26795244, 0.64042048, 0.57386098, 0.66834379,
       0.31608528, 0.10495893, 0.43526935, 0.8765499 , 0.26344833,
       0.75363025, 0.09871213, 0.91121645, 0.22025672, 0.99746309,
       0.84395337, 0.17576006, 0.7851246 , 0.39406109, 0.7886778 ,
       0.20780494, 0.37777774, 0.74970885, 0.59596454, 0.39278476,
       0.1592281 , 0.56206156, 0.17271736, 0.40174905, 0.57388638,
       0.19965739, 0.94495347, 0.59371655, 0.40185983, 0.59469096,
       0.17442778, 0.75414198, 0.1374889 , 0.47970139, 0.19921893,
       0.32261074, 0.96836888, 0.61535556, 0.27454708, 0.5603081 ,
       0.14141778, 0.00246889, 0.23310461, 0.36114133, 0.51363612,
       0.91745445, 0.49897583, 0.48482159, 0.4537013 , 0.81959

In [19]:
np.random.rand(5, 5)

array([[0.72467915, 0.01757915, 0.89541048, 0.58298843, 0.26426095],
       [0.97352722, 0.01109259, 0.24549981, 0.1663376 , 0.0685281 ],
       [0.45506739, 0.23926792, 0.62981414, 0.99550648, 0.21234992],
       [0.53396794, 0.58697897, 0.01449206, 0.22154056, 0.45171355],
       [0.98077798, 0.40014739, 0.62931803, 0.25748177, 0.53227094]])

In [20]:
np.random.randn(100)

array([ 1.13900843, -1.20908383,  0.32751196,  0.03912032,  0.80549294,
        0.18257531, -0.6322747 ,  1.91732685, -0.48098865, -1.00066337,
       -0.28080294,  2.02725586, -0.29090298,  0.79358711,  0.18078725,
        0.41860575,  0.31389873, -1.02723463, -0.39219101,  0.869987  ,
       -0.50598624,  1.4102206 ,  0.55081039,  0.84409653, -1.39360895,
       -0.10618217,  2.03445071,  0.70142586, -0.12297782, -2.37214084,
        0.34505013,  1.18841864, -0.10379332, -1.33961673,  1.35215186,
        0.47362545, -0.40931865,  1.17630759, -0.20804558, -0.60254976,
        0.03911222, -1.17501758, -0.8011897 ,  0.68711747, -0.40508786,
        1.44356865,  0.17391161,  0.43101637, -0.04055954, -0.24495499,
       -0.80542626, -0.60333432,  1.81090401,  0.23458624, -0.77588292,
       -0.39800352,  0.35388528, -0.05316693,  0.50489173,  0.15706535,
        2.06174525, -0.10086994, -0.92850655,  0.15310894, -0.7855773 ,
       -1.29062718,  2.22585032, -1.02998008, -0.82544374, -1.53

In [22]:
np.random.randn(2, 2)

array([[-0.03198404, -1.30084738],
       [ 0.64606073,  0.29613487]])

In [24]:
np.random.randint(1, 100)

8

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([28, 48, 45, 33, 25, 29, 44, 34, 22,  3])

In [32]:
ranarr.max()

48

In [33]:
ranarr.min()

3

In [36]:
ranarr.argmax()

1

In [37]:
arr.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.argmax()

24

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [47]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [51]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
slice_arr = arr[0:5]

In [54]:
slice_arr

array([100, 100, 100, 100, 100])

In [55]:
arr_copy = arr.copy()

In [56]:
slice_arr = arr[0:5]
slice_arr = [1,1,1,1]

In [58]:
arr_2d = np.array([[5,10,15],[10, 100, 5]])

arr_2d[0][0]

5

In [61]:
bool_arr = arr > 5

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [68]:
arr[arr>5]

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [70]:
arr = np.array([1,2,3])

In [71]:
arr

array([1, 2, 3])

In [72]:
arr * arr

array([1, 4, 9])

In [73]:
arr + arr

array([2, 4, 6])

In [74]:
arr - arr

array([0, 0, 0])

In [75]:
arr / arr

array([1., 1., 1.])

In [76]:
arr

array([1, 2, 3])

In [80]:
arr

array([1, 2, 3])

In [81]:
arr **2

array([1, 4, 9])

In [82]:
arr ** 3

array([ 1,  8, 27])

In [83]:
arr ** 5

array([  1,  32, 243])

In [84]:
arr**10

array([    1,  1024, 59049])

In [85]:
arr**100

array([                   1,                    0, -2984622845537545263])